richiestadocumento:
    path:     /{idCategoria}/{idRichiesta}
    defaults: { _controller: "estarRdaBundle:Richiestadocumento:index" }

richiestadocumento_show:
    path:     /{id}/show
    defaults: { _controller: "estarRdaBundle:Richiestadocumento:show" }

richiestadocumento_new:
    path:     /new
    defaults: { _controller: "estarRdaBundle:Richiestadocumento:new" }

richiestadocumento_create:
    path:     /create
    defaults: { _controller: "estarRdaBundle:Richiestadocumento:create" }
    methods:  POST

richiestadocumento_edit:
    path:     /{id}/edit
    defaults: { _controller: "estarRdaBundle:Richiestadocumento:edit" }

richiestadocumento_update:
    path:     /{id}/update
    defaults: { _controller: "estarRdaBundle:Richiestadocumento:update" }
    methods:  [POST, PUT]

richiestadocumento_delete:
    path:     /{id}/delete
    defaults: { _controller: "estarRdaBundle:Richiestadocumento:delete" }
    methods:  [POST, DELETE]

richiestadocumento_upload:
    path:     /upload/{idRichiesta}/{idDocumento}
    defaults: { _controller: "estarRdaBundle:Richiestadocumento:upload" }
    methods:  POST
